swagger: "2.0"
info:
  version: 1.0.0
  title: alto
  description: Mock API app for Alto
basePath: /api/v1
tags:
  - name: Trips
    description: Endpoints to retrieve trips
  - name: Specification
    description: The swagger API specification

consumes:
  - application/json
produces:
  - application/json


definitions:
  NoteBody:
    type: object
    title: A trip note
    required:
      - note
    properties:
      note:
        type: string
        example: Can you drop me off at AA International Bag Drop please?

paths:
  /trips:
    get:
      tags:
        - Trips
      description: Fetch all trips
      responses:
        200:
          description: Returns all trips
  /trips/current:
    get:
      tags:
        - Trips
      description: Get the current trip for the currently signed in user
      responses:
        200:
          description: Returns the current trip
  /trips/{id}:
    get:
      tags:
        - Trips
      parameters:
        - name: id
          in: path
          required: true
          description: The id of the trip to retrieve
          type: string
      responses:
        200:
          description: Return the trip with the specified id
        404:
          description: Trip not found
    delete:
      tags:
        - Trips
      parameters:
        - name: id
          in: path
          required: true
          description: The id of the trip to cancel
          type: string
      responses:
        204:
          description: The trip was cancelled successfully
  /trips/{id}/note:
    put:
      tags:
        - Trips
      parameters:
        - name: id
          in: path
          required: true
          description: The id of the trip to update
          type: string
        - name: note
          in: body
          description: The note you wish to set
          required: true
          schema:
            $ref: "#/definitions/NoteBody"
      responses:
        204:
          description: The note was updated successfully
        404:
          description: Trip not found

  /spec:
    get:
      tags:
        - Specification
      responses:
        200:
          description: Return the API specification