swagger: "2.0"
info:
  version: 1.0.0
  title: alto
  description: The Alto trip-service allows riders to track the status of their trips, get information
    about their driver, send their drivers notes, update the vibe of their trip,
    or flash some LEDs to identify their vehicle.
    </br><span style="color:red"><strong>NOTE!</strong>
    Use tripId 1234 with any of the below requests</span>
basePath: /api/v1
tags:
  - name: Trips
    description: Manage Trips
  - name: Specification
    description: The swagger API specification

consumes:
  - application/json
produces:
  - application/json


definitions:
  NoteBody:
    type: object
    title: Driver Note
    required:
      - note
    properties:
      note:
        type: string
        example: Can you drop me off at the Delta gate instead?
  VibeBody:
    type: object
    title: Trip Vibe
    required:
      - vibeId
    properties:
      vibeId:
        type: string
        example: FIZZ
  ColorBody:
    type: object
    title: Color
    required:
      - color
    properties:
      color:
        type: string
        example: '#FF0000'

paths:
  /trips/current:
    get:
      tags:
        - Trips
      description: Get the user's currently active trip (if there is one)
      responses:
        200:
          description: The user's currently active trip
        404:
          description: The trip was not found
  /trips/{id}:
    get:
      tags:
        - Trips
      description: Get a specific trip
      parameters:
        - name: id
          in: path
          required: true
          description: The id of the trip to retrieve
          type: string
      responses:
        200:
          description: The specified trip
        404:
          description: The trip was not found
    delete:
      tags:
        - Trips
      description: Cancel a trip in progress
      parameters:
        - name: id
          in: path
          required: true
          description: The id of the trip to cancel
          type: string
      responses:
        204:
          description: The trip was cancelled successfully
        404:
          description: The trip was not found
  /trips/{id}/updates:
    get:
      tags:
        - Trips
      description: Stream all updates for a particular trip. <span style="color:red"><strong>NOTE!:</strong>
        Swagger does not support Server-Sent Events at this time. Instead, open
        [this link](http://localhost:3000/api/v1/trips/1234/updates) in another tab, then come back here and make
        some updates (like cancelling a trip or updating the vibe!) and watch them stream in real time in your other
        tab.</span>
      parameters:
        - name: id
          in: path
          required: true
          description: The id of the trip to stream updates for
          type: string
      responses:
        200:
          description: Streams server-sent events with updates to the specified trip
        404:
          description: The trip was not found
  /trips/{id}/note:
    put:
      tags:
        - Trips
      description: Update the trip note
      parameters:
        - name: id
          in: path
          required: true
          description: The id of the trip to update the note for
          type: string
        - name: note
          in: body
          description: The updated note body
          required: true
          schema:
            $ref: "#/definitions/NoteBody"
      responses:
        204:
          description: The note was updated successfully
        404:
          description: The trip was not found
  /trips/{id}/vibe:
    put:
      tags:
        - Trips
      description: Update the vibe of your trip
      parameters:
        - name: id
          in: path
          required: true
          description: The id of the trip to update the vibe for
          type: string
        - name: vibe
          in: body
          description: The updated vibeId
          required: true
          schema:
            $ref: "#/definitions/VibeBody"
      responses:
        204:
          description: The vibe was updated successfully
        404:
          description: The trip was not found
  /trips/{id}/driver-contact-info:
    get:
      tags:
        - Trips
      description: Get the contact information for your driver
      parameters:
        - name: id
          in: path
          required: true
          description: The id of the trip to retrieve contact info for
          type: string
      responses:
        200:
          description: The contact information for the driver
        404:
          description: The trip was not found
  /trips/{id}/vehicle/identification-request:
    post:
      tags:
        - Trips
      description: Blink the LEDs on the front of your vehicle
      parameters:
        - name: id
          in: path
          required: true
          description: The id of the trip whose vehicle you want to identify
          type: string
        - name: color
          in: body
          description: The color to identify the vehicle with
          required: true
          schema:
            $ref: "#/definitions/ColorBody"
      responses:
        204:
          description: The vehicle was successfully identified
        404:
          description: The trip was not found

  /spec:
    get:
      tags:
        - Specification
      responses:
        200:
          description: Return the API specification